### PR TITLE
Possible and Default Value Changes

### PR DESCRIPTION
**Pull request by aeromax38**

### CODE REVIEW

**Comment by aeromax38** [comment]
I fixed it. Please review the other changes. Also, can you give the other files that have the values like the other ones that I changed? I couldn't find them...

**Comment by aeromax38** [comment]
Thanks for that catch lol

**Comment by aeromax38** [comment]
Should we push it now?

**Comment by DrDab** [comment]
Not yet, I'm still reviewing changes.

**Comment by DrDab** [comment]
Seems ok, we can merge this branch in. I will go ahead and give it a test. Good job

**Comment by aeromax38** [comment]
Okay

**Comment by aeromax38** [comment]
## Making Two New Repositories
Unless you really do not want to, I'm making a new repository each for the Pit Scouting app and the Match Scouting app. This is my process:
1. Clone this repository twice, naming one "TRC-Match-Scouting-App" and the other "TRC-Pit-Scouting-App".
2. Delete branches with code for the other app in it (inverse for each new repository).
3. Transfer ownership to you! (pending your go-ahead in response to this comment).

**Pull request merged**
